# -*- coding: utf-8 -*-
"""ML BC First Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jh3PjpZqe08IHvK9qWvwBB6aBlNUhag9
"""

print("Hello, World!")
print("Nafis Sadik\nMilestone College")

import sys
print(sys.version)

print("          (__)    \n  `|------(oo)\n    ||    (__)\n    ||w--||     ")
"""
Should look like this

          (__)
  `|------(oo)
    ||    (__)
    ||w--||

"""

"""
Overview: this is the part where the coder tell the new coder what's important for the code bellow
such as this code is only for assignment only.
The best part is that it can be wriiten in multilines
Usually used for Documentation or a message
Single line comment is used bellow.
"""
# Line 01: bellow lies is prompt to welcome the user and asking the user for a number input and storing it in a variable
number1 = int(input("Wlecome User, enter the first value "))

# line 02: bellow line is to check if user's number is even or not:
if(number1 % 2 == 0):
  isIt = "Yes"
else:
  isIt = "No"

# line 3: bellow line will tel the user if his number is even or not
print(isIt)

name = input("Your name:\n")
print(type(name))

age = int(input("\nYour age:\n"))
print(type(age))

height = float(input("\nYour heiight(cm):\n"))
print(type(height))

sudentStatus = input("\nStudet status:\nWrite True if you are else write False\n")
print(type(sudentStatus))

a = int(input("enter a value for a:\n"))
b = int(input("enter another value for b:\n"))

a,b = b,a

print("a is", a, "b is", b, "they were swaped!")

temCel = 32 #in celcius
temFah = (temCel * 1.2) + 32 #for Fahrenheit
temKel = temCel + 273 #for kelvin

print("in Fahrenheit:", temFah, "\nIn kelvin:", temKel)

num = "123"
wholeNum = 45
decimalNum = 9.8

convertNum = int(num) #to convert num to integer
print(convertNum, type(convertNum))

convertDeciaml = float(wholeNum) #to convert wholeNum to float
print(convertDeciaml, type(convertDeciaml))

convertWholeNum = int(decimalNum) #to convert decimalNum to integer
print(convertWholeNum, type(convertWholeNum))

mixed_data = [32, 13.4, "data", True, [1,2,3],]

for datum in mixed_data:
  print(datum, "-->", type(datum), "\n")

a = float(input("Enter value for a: \n"))
b = float(input("Enter value for b: \n"))

print("addition is:", a+b)
print("subtracton is:", a-b)
print("product is:", a*b)
print("devision is:", a/b)
print("devision result in whole number:", a//b)
print("reminder is:", a%b)
print("a to the power b is:", a**b)

a = int(input("Ente a value:\n"))
b = int(input("Enter another value:\n"))

if(a==b):
  print("They are equal!")
else:
  print("They are not equal!")
  if(a>b):
    print(a, "is greater")
  else:
    print(b, "is greater")

a = int(input("Ente a value:\n"))

#using logical and operator
if(a>=10  and a<=50):
  print("The number is within 10 to 50")
else:
  print("The number is not within 10 to 50")

#using logical or with not operator
if not(a<10  or a>50):
  print("The number is within 10 to 50")
else:
  print("The number is not within 10 to 50")

a = int(input("Ente a value:\n"))

if(a%3 == 0 and a%5 == 0):
  print("Divible")
else:
  print("Not divisibl")

a = int(input("Ente a value:\n"))

if(a<0):
  print("Negative number")
elif(a==0):
  print("Number is zero")
else:
  print("Positive number")

mark = int(input("Ente your mark:\n"))

i = 1

while i==1:
  if(mark>=0 and mark<=100):
    i = 0
  else:
    mark = int(input("Invalid mark!\nEnte your mark:\n"))

"""
GRADE SYSTEM
0 - 39     :F
40 - 59    :D
60 - 69    :C
70 - 79    :B
80 - 100   :A
"""

if mark<40:
  print("Your grade: F")
elif mark<60:
  print("Your grade: D")
elif mark<70:
  print("Your grade: C")
elif mark<80:
  print("Your grade: B")
elif mark<101:
  print("Your grade: A")

a = int(input("Ente a value:\n"))

if a >100:
  print("Number is above 100")
  if a%2 == 0:
    print("Number is even")
  else:
    print("Number is not even")
else:
  print("Number is less than 100")

a = int(input("Ente a value:\n"))
b = int(input("Ente another value:\n"))
c = int(input("Ente  one more another value:\n"))

if a>=b and a>=c:
  print("Greeast value is :", a)
elif b>=a and b>=c:
  print("Greatset value is :", b)
else:
  print("Greatest value is :", c)

for i in range(1, 21):
  print(i)

i =10
sum = 0
while i != 0:
  sum = sum + i
  i = i-1
print("Sum of the first 10 naural vlae is:", sum)

for i in range(1, 51):
  if(i%2!=0):
    continue
  print(i)

a = int(input("Ente a value to its factorial:\n"))

product = 1

for i in range(1, a+1):
  product = i*product

print("The factorial is:", product)

for i in range(1, 6):
  for j in range(1, i+1):
    print("*", end="")
  if(i!=5):
    print(end=" ")

fruits = ["mango", "banana", "guva", "watermelon", "apple"]
fruits.append("orange")
fruits.remove("guva")

print(fruits)

numbers = (1, 2, 3, 4, 5)
del sum
print("max =", max(numbers), "\nmin =", min(numbers), "\nsum =", sum(numbers))

info = [
    {
     "name": "xyz",
     "age": 28,
     "dept":"CSE",
    },
    {
     "name": "abc",
     "age": 18,
     "dept":"EEE"
    }
]

for i in info:
  print("Name:", i["name"])
  print("Age:", i["age"])
  print("dept:", i["dept"])
  print("---e-n-d---")

num1 = {1, 3, 6, 8, 11}
num2 = {2, 3, 5, 9, 11}

print("num1=", num1)
print("num2=", num2)
print("\n___---___---___---___---___\n")

print("num1 UNION num2: ", num1 | num2)
print("num1 INTERSECTION num2:", num1 & num2)
print("num1 DIFFERENCE num2", num1-num2)
print("num2 DIFFERENCE num1", num2-num1)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,]

for number in numbers:
  if(number%2==0):
    print(number)

name = input('Enter your name:\n')
age = int(input("Nter you age:\n"))
print("Hello ", name, ", you are ", age, " years old.",  sep="")

a = int(input("Enter value for a: \n"))
b = int(input("Enter value for b: \n"))

print("addition is:", a+b)
print("difference is:", abs(a-b))
print("product is:", a*b)

a = int(input("Enter value for lenght: \n"))
b = int(input("Enter value for width: \n"))

print("The area of the rectangle is:", a*b, "square unit")